# Generated by Django 5.1.15 on 2026-09-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(default='Government Services', max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('short_desc', models.CharField(help_text='One-line summary in plain words', max_length=300)),
                ('benefits', models.TextField(help_text='One benefit per line')),
                ('documents_required', models.TextField(help_text='One document per line')),
                ('apply_url', models.URLField(blank=True)),
                ('max_income', models.PositiveIntegerField(blank=True, help_text='Annual family income cap in INR; blank = no cap', null=True)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('max_age', models.PositiveIntegerField(default=120)),
                ('allowed_categories', models.CharField(blank=True, help_text='Comma-separated codes (sc,st,obc,ews,minority,general); blank = all', max_length=200)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='any', max_length=10)),
                ('education_level', models.CharField(choices=[('any', 'Any'), ('school', 'School'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], default='any', max_length=20)),
                ('state', models.CharField(blank=True, help_text='Blank = all India', max_length=100)),
                ('students_only', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('annual_income', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS'), ('minority', 'Minority')], max_length=20)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('education_level', models.CharField(choices=[('any', 'Any'), ('school', 'School'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.scheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
