# Generated by Django 5.1.15 on 2026-09-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhaar_linked',
            field=models.BooleanField(default=False, verbose_name='Aadhaar-linked bank account'),
        ),
        migrations.AddField(
            model_name='application',
            name='achievements_notes',
            field=models.TextField(blank=True, verbose_name='Key achievements summary'),
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='board_10th',
            field=models.CharField(blank=True, max_length=100, verbose_name='10th Board'),
        ),
        migrations.AddField(
            model_name='application',
            name='board_12th',
            field=models.CharField(blank=True, max_length=100, verbose_name='12th Board'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_course',
            field=models.CharField(blank=True, max_length=150, verbose_name='Current course / stream'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current institution name'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Current year / semester'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='application',
            name='disability_status',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10, verbose_name='Disability status'),
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('student', 'Student / Not employed'), ('intern', 'Internship'), ('employed', 'Employed / Working'), ('other', 'Other')], default='student', max_length=50, verbose_name='Employment / Internship status'),
        ),
        migrations.AddField(
            model_name='application',
            name='latest_percentage',
            field=models.CharField(blank=True, max_length=20, verbose_name='Latest % or CGPA'),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage_10th',
            field=models.CharField(blank=True, max_length=20, verbose_name='10th % / CGPA'),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage_12th',
            field=models.CharField(blank=True, max_length=20, verbose_name='12th % / CGPA'),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarships_availed',
            field=models.TextField(blank=True, verbose_name='Scholarships already availed (if any)'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='restrict_to_listed_institutions',
            field=models.BooleanField(default=False, help_text='Restrict eligibility to listed approved institutions only'),
        ),
        migrations.AlterField(
            model_name='application',
            name='annual_income',
            field=models.PositiveIntegerField(verbose_name='Family annual income (Rs)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(choices=[('any', 'Any'), ('school', 'School'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], max_length=20, verbose_name='Current education level'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Achievement title')),
                ('level', models.CharField(choices=[('school', 'School'), ('state', 'State'), ('national', 'National'), ('international', 'International')], default='school', max_length=50, verbose_name='Level')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='Year')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Approved school / college / university name', max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_institutions', to='core.scheme')),
            ],
            options={
                'verbose_name': 'Approved Institution',
                'verbose_name_plural': 'Approved Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Institution name')),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], default='school', max_length=50, verbose_name='Type')),
                ('board_affiliation', models.CharField(blank=True, max_length=150, verbose_name='Board / Affiliation')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('years_attended', models.CharField(blank=True, max_length=50, verbose_name='Years attended')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions_attended', to='core.application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
