# Generated by Django 5.1.15 on 2026-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_aadhaar_linked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='disability_status',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10, verbose_name='Disability status'),
        ),
    ]
