# Generated by Django 5.1.15 on 2026-09-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_disability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='any', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS'), ('minority', 'Minority')], default='general', max_length=20)),
                ('annual_income', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(choices=[('any', 'Any'), ('school', 'School'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], default='undergraduate', max_length=20)),
                ('current_institution', models.CharField(blank=True, max_length=200)),
                ('is_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false to unsubscribe from alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='sent', max_length=20)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('matched_reasons', models.TextField(blank=True, help_text='Summary of matching criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.scheme')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.studentsubscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('subscriber', 'scheme')},
            },
        ),
    ]
